### ISSUE TITLE
240723_[不明][初期設定の不備？] 必要ドライバの未インストール_データ取得、カメラによる撮像が出来ない

### ISSUE THREAD

**Issue by DKST-support-desk** [DKST-support-desk/DKST_Type1#13]
製造部からの不具合対応依頼です

【不具合内容】

サーマル製造２部生産９課　熊谷です。
お世話になっております。

```
Ｔ２ラインの４工程、全てデーターの吸い上げができずカメラ撮影×の状態です。
配線確認、再起動等実施しましたが解決しません。
お忙しい中、申し訳ありませんが確認して頂けないでしょうか。
よろしくお願いします。
```

IT　資産No　　0001　003444

対応予想
- インスタンスパスの不整合
- カメラのドライバが正常に動かない or バージョンが低い or ドライバが入ってない のどれかかと思いますので、公式サイトからドライバをインストールして動作確認を行う
https://github.com/user-attachments/assets/e5e73ac7-e9c4-47a9-9212-096231d0db79

**Comment by DKST-support-desk** [comment]
何回か確認したが電源入ってないので、入れるよう依頼
![image](https://github.com/user-attachments/assets/951caef2-0601-450d-9b05-c51c015b44ba)

**Comment by DKST-support-desk** [comment]
@Zin-Denso 
こちらって何か対応されました？？

カメラが正常に動いてる気がするのですが
![image](https://github.com/user-attachments/assets/71c90b7b-d36d-4edb-9929-02f6c69590ec)

**Comment by Zin-Denso** [comment]
特に何も触っていませんが、PCにリモート接続しに行き動作確認したところ、問題なく動いているように見えます。

**Comment by DKST-support-desk** [comment]
誰も何もしてないが、自然と復旧したみたい
もはや追えないのでクローズ
