### ISSUE TITLE
近接スイッチの感度が悪く正常にサイクルが取れないよ問題

### ISSUE THREAD

**Issue by babaaan** [DKST-support-desk/DKST_Type1#7]
> 以前ですが前任の原さんに各工程の近接スイッチの感度が悪く正常にサイクルが取れないと
打ち上げたところ検知範囲の長い近接スイッチを購入し渡してくれると仰ってましたが
その後、入荷されましたでしょうか。
また、T3ラインのDKSTにて４工程のうち１・２工程がデータが吸い上げ出来ず
配線の見直し、立ち上げ直しなどしましたが解決しません
すいませんが見て頂けないでしょうか。
お忙しいところすいませんがお願いします

現場から上記のメール

**Comment by babaaan** [comment]
資産Noは0001001870

**Comment by DKST-support-desk** [comment]
@Yuichi-Hara 

> 検知範囲の長い近接スイッチを購入し渡してくれる   

という件、進捗を教えてください。
→ 購入済みで現場へ渡し済み
